Changed EventSubscriber template
TheSoftwareHouse/express-boilerplate pull request #11
Opened 2020-12-02 08:51 UTC by low-cpu

#10 fix

2020-12-02 09:00 UTC, sethii reviewed
I would keep comments - maybe it is not an example, but still might be harder to understand without it.

2020-12-02 10:14 UTC, sethii requested changes

2020-12-02 10:14 UTC, sethii commented on plop-templates/events/event-subscriber.ts
> +    return [{ name: {{pascalCase name}}Event.eventName, method: this.log{{pascalCase name}}.name }];
`this.log{{pascalCase name}}.name }` di you try if this is working. The thing is I am afraid it will break the context of a "this", so inside the method we won't have an access to subscriber dependencies. Pleas check it.

2020-12-02 10:52 UTC, low-cpu commented on plop-templates/events/event-subscriber.ts
> +    return [{ name: {{pascalCase name}}Event.eventName, method: this.log{{pascalCase name}}.name }];
I use this approach in my project and it works fine.

2020-12-04 08:14 UTC, sethii approved these changes

2020-12-04 08:14 UTC, merged